version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    networks:
      - app-network
    ports:
      - 3000:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=mindfulu

  backend:
    build: backend/
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build: frontend/
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes: 
      - ./frontend/src:/frontend/src
    command: npm run dev
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_container
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
