version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 3000:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=mindfulu

  backend:
    build: backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    volumes: 
      - ./frontend/src:/frontend/src
    command: npm run dev
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    ports:
      - "8010:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
