# Generated by Django 4.1.12 on 2023-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Event Name', max_length=255)),
                ('date', models.CharField(default='Event Date', max_length=100)),
                ('duration', models.CharField(default='Event Duration', max_length=100)),
                ('day', models.CharField(default='Event Day', max_length=30)),
                ('time', models.CharField(default='Event Time', max_length=50)),
                ('venue', models.CharField(default='Event Venue', max_length=255)),
                ('registration', models.TextField(default='Registration Information')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scraped_content', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Scraped Data',
                'verbose_name_plural': 'Scraped Data',
            },
        ),
    ]
