# Generated by Django 4.1.13 on 2023-11-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_supportlink_alter_mood_mood_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportlink',
            name='link_url',
        ),
    ]
