# Generated by Django 4.1.13 on 2023-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_supportlink_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportlink',
            name='link_url',
            field=models.URLField(default=''),
        ),
    ]
