# Generated by Django 4.1.13 on 2023-11-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_supportlink_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='supportlink',
            options={},
        ),
        migrations.RemoveField(
            model_name='supportlink',
            name='url',
        ),
        migrations.AlterField(
            model_name='supportlink',
            name='link_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supportlink',
            name='link_url',
            field=models.URLField(),
        ),
        migrations.AddField(
            model_name='supportlink',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.supportsection'),
        ),
    ]
