# Generated by Django 4.1.13 on 2023-11-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_supportsection_alter_supportlink_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='user',
            new_name='user_id',
        ),
    ]
