# Generated by Django 4.1.13 on 2023-11-13 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_alter_friendship_friend_alter_friendship_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL),
        ),
    ]
