# Generated by Django 4.1.13 on 2023-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_mood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood_cause',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Financial', 'Financial'), ('Relationship/Social', 'Relationship/Social'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
