# Generated by Django 4.1.13 on 2023-12-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_profileinfo_delete_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
