# Generated by Django 4.1.13 on 2023-12-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
