# Generated by Django 4.1.13 on 2023-12-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_userprofile_picture_userprofile_show_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show_mood',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
